# Generated by Django 3.1.2 on 2021-09-26 22:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name="Nom de la catégorie d'objet")),
                ('slug', models.SlugField(blank=True, help_text='Laissez vide pour que le champ se remplisse seul', verbose_name='Slug')),
                ('short_description', models.TextField(blank=True, verbose_name='description courte')),
            ],
            options={
                'verbose_name': "Catégorie d'objet",
                'verbose_name_plural': "Catégories d'objet",
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='Nom de la couleur')),
                ('slug', models.SlugField(blank=True, help_text='Laissez vide pour que le champ se remplisse seul', verbose_name='Slug')),
                ('code', models.CharField(db_index=True, max_length=256, verbose_name='Code de la couleur')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Couleur',
                'verbose_name_plural': 'Couleurs',
            },
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='Nom du designer')),
                ('slug', models.SlugField(blank=True, help_text='Laissez vide pour que le champ se remplisse seul', verbose_name='Slug')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description du designer')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Designer',
                'verbose_name_plural': 'Designers',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='Nom du matériau')),
                ('slug', models.SlugField(blank=True, help_text='Laissez vide pour que le champ se remplisse seul', verbose_name='Slug')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description du matériau')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Matériau',
                'verbose_name_plural': 'Matériaux',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name="Etat de l'objet")),
                ('slug', models.SlugField(blank=True, help_text='Laissez vide pour que le champ se remplisse seul', verbose_name='Slug')),
            ],
            options={
                'verbose_name': "Etat de l'objet",
                'verbose_name_plural': "Etat de l'objet",
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='Nom du style')),
                ('slug', models.SlugField(blank=True, help_text='Laissez vide pour que le champ se remplisse seul', verbose_name='Slug')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description du style')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Style',
                'verbose_name_plural': 'Styles',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name="Nom de la sous catégorie d'objet")),
                ('slug', models.SlugField(blank=True, help_text='Laissez vide pour que le champ se remplisse seul', verbose_name='Slug')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="description du type d'objet")),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='filters.category', verbose_name='Categorie')),
            ],
            options={
                'verbose_name': "Sous catégorie d'objet",
                'verbose_name_plural': "Sous catégories d'objet",
            },
        ),
    ]
